pipeline:
  build:
    image: golang:1.8
    commands:
      - export GOPATH=/drone
      - export PATH=$PATH:$GOPATH/bin
      - go get -t -v ./...
      - go run main.go
      # - go get github.com/mattn/goveralls
      # - goveralls -service=drone.io -repotoken=${REPOTOKEN}

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=mysecretpassword
