workspace:
  base: /go
  path: src/github.com/bhechinger/drone-testing

pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go get -t -v ./...
      - go test
      # - go run main.go
      # - go get github.com/mattn/goveralls
      # - goveralls -service=drone.io -repotoken=${REPOTOKEN}

matrix:
  GO_VERSION:
    - 1.7
    - 1.8
  DATABASE:
    - mysql
    - mariadb
    - postgres

services:
  databashttps://drone.aba-eve.com/bhechinger/drone-testing/28e:
    image: ${DATABASE}
    environment:
      - POSTGRES_USER=myapp
      - POSTGRES_DB=myapp
      - POSTGRES_PASSWORD=mysecretpassword
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=mysecretpassword

