workspace:
  base: /go
  path: src/github.com/bhechinger/drone-testing

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get -t -v ./...
      - go test
      # - go run main.go
      # - go get github.com/mattn/goveralls
      # - goveralls -service=drone.io -repotoken=${REPOTOKEN}

matrix:
  mysql:
    - mysql
    - mariadb
  pgsql:
    - postgres

services:
  postgres:
    image: ${pgsql}
    environment:
      - POSTGRES_USER=myapp
      - POSTGRES_DB=myapp
      - POSTGRES_PASSWORD=mysecretpassword
  mysql:
    image: ${mysql}
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=mysecretpassword

