workspace:
  base: /go
  path: src/github.com/bhechinger/drone-testing

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get -t -v ./...
      - sleep 15
      - go run main.go
      # - go get github.com/mattn/goveralls
      # - goveralls -service=drone.io -repotoken=${REPOTOKEN}

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=mysecretpassword
